
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATEGORIA COLON DASH DOUBLECOLON NOME NUMERO SEMICOLON VALORcategorias : categoriacategorias : categorias categoriacategoria : CATEGORIA COLON produtosprodutos : produtoprodutos : produtos produtoproduto : DASH NUMERO DOUBLECOLON NOME DOUBLECOLON VALOR DOUBLECOLON NUMERO SEMICOLON'
    
_lr_action_items = {'CATEGORIA':([0,1,2,4,6,7,9,17,],[3,3,-1,-2,-3,-4,-5,-6,]),'$end':([1,2,4,6,7,9,17,],[0,-1,-2,-3,-4,-5,-6,]),'COLON':([3,],[5,]),'DASH':([5,6,7,9,17,],[8,8,-4,-5,-6,]),'NUMERO':([8,15,],[10,16,]),'DOUBLECOLON':([10,12,14,],[11,13,15,]),'NOME':([11,],[12,]),'VALOR':([13,],[14,]),'SEMICOLON':([16,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'categorias':([0,],[1,]),'categoria':([0,1,],[2,4,]),'produtos':([5,],[6,]),'produto':([5,6,],[7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> categorias","S'",1,None,None,None),
  ('categorias -> categoria','categorias',1,'p_categorias_single','parser.py',17),
  ('categorias -> categorias categoria','categorias',2,'p_categorias_recursive','parser.py',21),
  ('categoria -> CATEGORIA COLON produtos','categoria',3,'p_categoria','parser.py',25),
  ('produtos -> produto','produtos',1,'p_produtos_single','parser.py',33),
  ('produtos -> produtos produto','produtos',2,'p_produtos_recursive','parser.py',37),
  ('produto -> DASH NUMERO DOUBLECOLON NOME DOUBLECOLON VALOR DOUBLECOLON NUMERO SEMICOLON','produto',9,'p_produto','parser.py',41),
]
